### ISSUE TITLE
17.09 release

### ISSUE THREAD

**Issue by Moredread** [nix-community/nixbox#24]
Is there anything blocking the release of an updated version?

**Comment by zimbatm** [comment]
Mainly manpower to bump the channel and do a bit of testing.

The project used to have some automation in place to build the images but that might be broken.

If you're willing to do the first part I would be up for looking into the second-one.

**Comment by Moredread** [comment]
I can't promise at the moment when I'll have free time for this. :/ But I let you know when I'll try it.

**Comment by PierreR** [comment]
FWIW I am using the x86_64 updated to 17.09 and it works as nicely as with 17.03 (I sometimes encountered problem with packer but I don't think there are related to the update as I had them before)

**Comment by Moredread** [comment]
Has there been any update in the meantime?

**Comment by zimbatm** [comment]
Yes, the box is now at 18.09
