### ISSUE TITLE
Unknown --chroot argument

### ISSUE THREAD

**Issue by PierreR** [nix-community/nixbox#31]
Trying to build the box with 18.03, I have got the error that `--chroot` is not a recognized option.

I guess it has been removed ?

https://github.com/nix-community/nixbox/blob/master/scripts/install.sh#L34

**Comment by daveman1010221** [comment]
I am also running into problems with this on an UEFI MacBook Pro, which is further causing issues when grub tries to install to /boot, instead of /mnt/boot and causes nixos-install to fail out. :-(

**Comment by zimbatm** [comment]
@daveman1010221 try reporting on https://github.com/nixos/nixpkgs

The argument has been removed in 18.03 and now defaults to /mnt. This is fixed in the latest nixbox release.
