### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by LucianU** [nix-community/nixbox#48]
Hello!

Is there any reason why there haven't been any releases on Vagrant Cloud since 18.09? Is it possible to release a box for 19.03?

**Comment by zimbatm** [comment]
Hi!

Yes, see this related issue: https://github.com/nix-community/nixbox/issues/38#issuecomment-451085234

**Comment by LucianU** [comment]
@zimbatm, thanks! Closing this since it's a duplicate.
