### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixbox#75]
I haven't touched VirtualBox for years now, I think it's time to pass on the maintenance.

Please leave a message here if you're interested in taking this project up.

**Comment by gurjeet** [comment]
@zimbatm, I would like to volunteer my time building and maintaining these packages. I am a devout Vagrant+Virtualbox user, and have mucked with Vagrantfiles enough in the past to think that I can take on this responsibility.

You will have to help me with some pointers to get started, though.

**Comment by zimbatm** [comment]
Great! Tell me what you need to get started.

If I were you I would probably take a look at the code to see what makes sense, take some notes and then ask questions. send PRs, ... The project hasn't been touched for a while so there are probably some Vagrant best practices that we don't follow.

Let me know

**Comment by zimbatm** [comment]
Make yourself at home. Once I start seeing PRs flowing I'm happy to transfer the maintainership.

**Comment by zimbatm** [comment]
Fixed in https://github.com/nix-community/nixbox/issues/89#issuecomment-1880066086

**Comment by ifurther** [comment]
Thank you @zimbatm
