### ISSUE TITLE
Support for Virtualbox 7.0+

### ISSUE THREAD

**Issue by pmaterer** [nix-community/nixbox#87]
I was trying to build `virtualbox-iso.virtualbox` on macOS 12.4 using Virtualbox 7.0.4, and I noticed the HTTP server Packer creates was not reachable. After some research I found the issue [here](https://github.com/hashicorp/packer/issues/12118). With VBox 7.0+, the config option `--nat-localhostreachable` was introduced and is set to `off` by default.

So to fix the issue something like this will need to be done:

```hcl
source "virtualbox-iso" "virtualbox" {
...
  vboxmanage           = [["modifyvm", ..., "--nat-localhostreachable1", "on"]]
...
}
```

With that in place the build works on Virtualbox 7.0+. However I *haven't* tested if this breaks builds with older versions of VBox.

**Comment by pdietl** [comment]
Hello @pmaterer, I submitted a fix for this to the virtual box plugin directly: https://github.com/hashicorp/packer-plugin-virtualbox/pull/122

**Comment by ifurther** [comment]
It's not working old version

**Comment by pdietl** [comment]
Yeah @ifurther the PR I mentioned above should work on old and new versions.
